### ISSUE TITLE
Cannot boot linux with USB hub

### ISSUE THREAD

**Issue by ofauchon** [jimdigriz/debian-mssp4#1]
Hi. 

What I did : 
- disable secure boot
- change boot order USB=>Internal

And then ... 
- I CAN boot a USB key when plugged in the Surface 4, but I don't have keyboard
- I CAN'T boot the same USB Key when plugged in a USB2 or USB3 hub (self powered, or with external power). 
  Note 1: Windows starts booting like there is no USB device available.
  Note 2: Computer sees the key contents (New drive in file manager) when Windows 10 starts

It seems there is incompatibility between hub, usb key, and surface at boot. 
Any help welcome.

PS: My linux bootable usb key was ArchLiinux iso. 
But that should not change the behaviour AFAIK.

Olivier

**Comment by jimdigriz** [comment]
I too found the EFI BIOS really gets annoyed about USB hubs too, luckily it was not a problem for me...

For myself, once you have booted the install media for Linux (this works for Debian) and have hit the first menu, you should be able to unplug the USB key, then plug in a hub with the keyboard and USB key attached.  Linux will detect everything with no problems.

The install process will then afterwards mount the USB key as it 'looks for a CD' or something; this is how I got Debian on there with no trouble.

Makes sense?

**Comment by ofauchon** [comment]
Ok, the problem was solved by using another usb key (in fact a USB to microSD adapter). 
I still use no-name usb3 hub, and external usb keyboard works fine too. 

Time to resume Linux installation
