### ISSUE TITLE
Can't find the specified kernel version

### ISSUE THREAD

**Issue by RabidBurn** [jimdigriz/debian-mssp4#17]
Hello,
When I originally followed this guide, it was for kernel 4.6, but now I'm trying to update.
I can't find the file linux-source-4.8_4.8.7-1_all.deb, maybe I'm doing something wrong.
The closest file I can find is linux-source-4.8_4.8.15-2_all.deb but these instructions with that file produce a kernel panic on shutdown... Note, I'm on Kali linux, but this didn't cause any problems when I was updating to 4.6 so I'm hoping it will continue to not cause any problems.
I'm not too experienced with manually doing kernel stuff like this, but I'm assuming that your code won't work on this file?

I'm fine with using the kernel version you specify, I just can't find the file...

**Comment by jimdigriz** [comment]
Looks like you the info you need lurks in the [Recompiling the Kali Linux Kernel](http://docs.kali.org/development/recompiling-the-kali-linux-kernel) instructions.  There is a [list of Kali Linux kernel versions](http://http.kali.org/kali/pool/main/l/linux-latest/) too and the current one (at a guess as I am no Kali Linux user) is `4.8+77+kali1`.

To be honest though, you should be able to speak to someone involved in Kali and helps its users (mailing lists, IRC channels, etc) show them my instructions and they will be able to tell you what changes are needed.

Good Luck

**Comment by RabidBurn** [comment]
Ok, thanks for the info!
