### ISSUE TITLE
Helpful link to resize resolution

### ISSUE THREAD

**Issue by G5unit** [jimdigriz/debian-mssp4#3]
Hi,

Great page, thanks for putting it together. I want to share a link that helped me use xrandr to change the resolution on the screen to something smaller so I do not go blind :) ..
http://superuser.com/questions/347437/xorg-how-to-specify-a-non-standard-display-resolution

My script I run at logon:
###### 

xrandr --newmode "1680x1050_60.00" 146.25 1680 1784 1960 2240 1050 1053 1059 1089 -hsync -vsync
xrand --addmode eDP1 1680x1050_60.00
xrandr --output eDP1 --mode 1680x1050_60.00 --set "scaling mode" Full
###### 

Cheers.

**Comment by jimdigriz** [comment]
I really recommend trying to go with the [HiDPI](https://wiki.archlinux.org/index.php/HiDPI) path so that your fonts are actually larger, as well as all the widgets and images on your desktop.

This way you get a nice crisp display where the fonts and images look really good.
