### ISSUE TITLE
Boot Surface Pro 4 from usb stick?

### ISSUE THREAD

**Issue by pwFoo** [jimdigriz/debian-mssp4#5]
Hi I get an Surface Pro 4 and tried to boot from any usb stick without success.
- ubuntu / centos iso written with dd to usb stick
- yumi multi boot stick with centos, ubuntu and manjaro linux
- easy2boot with ubuntu, centos, manjaro 

Each time the "surface" text jitters and some seconds later Win10 is booting up...

Tested with secure boot and / or tpm off. usb is 1st boot media. Also tested with internal disk disabled. No change to get usb boot working.

Any idea how to boot my sp4 from usb media?

**Comment by jimdigriz** [comment]
Though the first boot media, does it also have a small black box next to 
the option indicating USB booting is enabled?

Does the USB stick boot fine on other _EFI_ laptops (this will tell you if 
the USB stick is faulty or not)?

In the instructions, I do not move the USB boot order about, I use one of 
two methods, have you read my instructions (I guess not as you are asking 
for help for every distro under the sun _except_ Debian) on how to boot off 
USB?  Here they are:

https://github.com/jimdigriz/debian-mssp4/blob/master/README.md#shrinking-the-windows-partition

Those two methods work fine...from your issue report it sounds like you 
have not tried either of these....?

Here's a crazy idea...have you tried booting a USB  Debian image or 
gparted, as per my instructions?  Those work, complaining something else is 
not booting is not something I can help with.

**Comment by pwFoo** [comment]
Hi @jimdigriz 

thanks for your answer. 

It looks like a problem with the surface pro 4, because all usb media boot up fine with my dell notebook.

I tested
- different linux distributions (debian, manjaro, centos, ubuntu,...) with dd to usb stick
- yumi multi boot stick
- easy2boot multi boot stick (uefi / efi support)

Latest test was a created Win10 recovery usb disk (created by the Win10 system recovery). This one works fine with both! Dell and also the SP4?!

>  secure boot and / or tpm off

Settings should be fine I think?

I fail before I could try to shrink the disk or install debian. So the problem isn't related to your howto, but it prevents me to follow your instructions.
Maybe you have an idea how to solve this, because I would love to run debian on my SP4...

**Comment by jimdigriz** [comment]
When `dd`ing, do you include `conv=fdatasync`?

**Comment by pwFoo** [comment]
Yes, tested without and with conv=fdatasync. It just boots up the installed Win10...
SP4 looks buggy to me, because also Chrome dies often in the first 5 minutes after Win10 is booted. 

Last chance is a Win10 reset and test it again. If it doesn't work it looks like a damaged hardware / firmware...

**Comment by jimdigriz** [comment]
Good luck with it.  I might dig around for a USB stick and check if things still work as detailed in my documentation, I have done a few firmware updates under Win10 since I last tried though.

Do let me know how it works out for you.

**Comment by pwFoo** [comment]
After sucessfully finished recovery all strange problems are gone! 

gparted stick was also bootable created with **Tuxboot** instead of dd... So I think also Debian should boot now. I'll try it in the next days. :)

Thanks for support here and thanks for that great howto! 
I'll test it soon, but first I have to reinstall needed software and take care about some other tasks because vacation is over now... :(
