### ISSUE TITLE
Touch screen , pen touch

### ISSUE THREAD

**Issue by holyprot** [jimdigriz/debian-mssp4#9]
Hi
Sorry for disturbing you , i know , I shouldn't ask for ETA.
But i think touch is inportant , sorry again .
Abd thx alot 😊

**Comment by jimdigriz** [comment]
These are instructions to get as much of the Surface Pro 4 working under Debian.

**Comment by jimdigriz** [comment]
https://github.com/jimdigriz/ipts-linux/blob/ipts-v4.6.x/README-IPTS.md I don't want to hear any complaints... :)

**Comment by holyprot** [comment]
thx alot :-)

**Comment by jimdigriz** [comment]
https://github.com/ipts-linux-org/ipts-linux-new
